# Generated by Django 3.1.4 on 2020-12-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='name',
            new_name='title',
        ),
    ]
